language: minimal

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install libgtk-3-dev

services:
  - docker

install:
  - docker pull jjmerelo/raku-test

script: docker run -t -v  $TRAVIS_BUILD_DIR:/test jjmerelo/raku-test
