os: Visual Studio 2017

platform: x64

install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
  - appveyor-retry choco install strawberryperl --allow-empty-checksums
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - git clone https://github.com/tadzik/rakudobrew %USERPROFILE%\rakudobrew
  - SET PATH=%USERPROFILE%\rakudobrew\bin;%PATH%
  - rakudobrew build moar %TEST_MOAR%
  - rakudobrew build zef
  - cd %APPVEYOR_BUILD_FOLDER%
  - echo "installing SSL so we can download the dll files"
  - zef install IO::Socket::SSL
  - zef --depsonly install .
  - zef build .

build: off

test_script:
  - prove -v -e "perl6 -Ilib" t/
  - zef --debug install .

shallow_clone: true