os: Visual Studio 2017

platform: x64

install:
  - vcpkg install gtk:x64-windows liblzma:x64-windows libxml2:x64-windows zstd:x64-windows

build_script:
  - echo "success"

shallow_clone: true

on_finish:
  - 7z a C:/dlls_packaged.zip C:/Tools/vcpkg/installed/x64-windows/bin/*.dll C:/Tools/vcpkg/installed/x64-windows/bin/*.pdb
  - appveyor PushArtifact C:/dlls_packaged.zip
